In [1]:
import numpy as np

x = np.array([1, 2])
print (x.dtype)

x = np.array([1.0, 2.0])
print (x.dtype)

x = np.array([1, 2], dtype=np.int64)
print (x.dtype)

int32
float64
int64


In [5]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print (x + y)
print (np.add(x, y))

print (x - y)
print (np.subtract(x, y))

print (x * y)
print (np.multiply(x, y))

print (x / y)
print (np.divide(x, y))

print (np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [6]:
#벡터 내적
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print (v.dot(w))
print (np.dot(v, w))

print (x.dot(v))
print (np.dot(x, v))

print (x.dot(y))
print (np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [7]:
# sum 
x = np.array([[1,2],[3,4]])

print (np.sum(x))
print (np.sum(x, axis=0))
print (np.sum(x, axis=1)) 

10
[4 6]
[3 7]
